#!/usr/bin/env python
# -*- coding: iso-8859-15 -*-
# generated by wxGlade 0.6.3 on Mon Jan 17 15:41:18 2011

import wx
from WindowMain import WindowMain


class MainApp(wx.App):
    """
	This is the initalization function called from within wxPython.
	"""
    def OnInit(self):
        wx.InitAllImageHandlers()
        self.wndMain = WindowMain(None, -1, "")
        self.SetTopWindow(self.wndMain)
        self.wndMain.Show()
        self.openFile = ""
        return 1
    def SetOpenFile(self, file):
        self.openFile = file
    def GetOpenFile(self):
        return self.openFile
    def LogMessage(self, message):
        self.wndMain.lstActivity.Append(message)
    def SetBenchWidget(self, w):
        self.benchWidget = w
    def GetBenchWidget(self):
        return self.benchWidget
    def ResetApplication(self):
        self.wndMain.Destroy()
        self.wndMain = WindowMain(None, -1, "")
        self.SetTopWindow(self.wndMain)
        self.wndMain.Show()
        self.openFile = ""

# end of class MainApp

if __name__ == "__main__":
    IntrospectionDemo = MainApp(0)
    IntrospectionDemo.MainLoop()
