#!/usr/bin/env python
# -*- coding: iso-8859-15 -*-
# generated by wxGlade 0.6.3 on Mon Apr 11 19:42:24 2011

import wx
#from ObjectPanel import ObjectPanel

# begin wxGlade: extracode
# end wxGlade



class WindowObjectPicker(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: WindowObjectPicker.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        objs = wx.GetApp().GetBenchWidget().getObjectNames()
        if len(objs) < 1:
            objs = [' ']
        self.lstObjects = wx.ListBox(self, -1, choices=objs)

        self.btnPick = wx.Button(self, -1, "Pick Object")
        self.btnPick.Bind(wx.EVT_BUTTON, self.OKClick)
        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: WindowObjectPicker.__set_properties
        self.SetTitle("Pick Object")
        self.SetSize((300, 300))
        self.lstObjects.SetSelection(0)
        self.btnPick.SetFocus()
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: WindowObjectPicker.__do_layout
        szMain = wx.BoxSizer(wx.VERTICAL)
        szMain.Add(self.lstObjects, 2, wx.EXPAND, 0)
        szMain.Add(self.btnPick, 0, wx.EXPAND, 0)
        self.SetSizer(szMain)
        self.Layout()

    def OKClick(self, event):
        self.EndModal(1)

    def GetSelected(self):
        return "[" + self.lstObjects.GetItems()[self.lstObjects.GetSelection()] + "]"
        # end wxGlade

# end of class WindowObjectPicker
