#!/usr/bin/env python
# -*- coding: iso-8859-15 -*-
# generated by wxGlade 0.6.3 on Sat Feb 12 14:14:14 2011

import wx
from IntrospectionTools import *
# begin wxGlade: extracode
# end wxGlade



class WindowObjectInspector(wx.Dialog):
    def __init__(self, introspectionObject, *args, **kwds):
        # begin wxGlade: WindowObjectInspector.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.lblObjNameDesc = wx.StaticText(self, -1, "Object Name:")
        self.lblObjName = wx.StaticText(self, -1, introspectionObject.getObjectName() )
        self.lblClassNameDesc = wx.StaticText(self, -1, "Class:")
        self.lblClassName = wx.StaticText(self, -1, introspectionObject.getObjectTypeName() )
        self.LblObjectIDDesc = wx.StaticText(self, -1, "Object ID:")
        self.lblObjectID = wx.StaticText(self, -1, str(introspectionObject.getObjectID()))

        self.attributes = introspectionObject.getObjectAttribs( False, True )
        self.attribLabels = []
        self.attribTexts = []
        self.introspectionObject = introspectionObject
        for a in self.attributes:
            self.attribLabels.append( wx.StaticText(self, -1, a) )
            self.attribTexts.append( wx.TextCtrl(self, -1, "?") )

        self.__set_properties()
        self.__do_layout()
        self.Bind(wx.EVT_CLOSE, self.onCloseWindow)

        self.timer = wx.Timer(self, 100)
        self.timer.Start(750)
        wx.EVT_TIMER(self, 100, self.refreshVars)
        self.refreshVars(None)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: WindowObjectInspector.__set_properties
        self.SetTitle("Object Inspector")
        self.lblObjNameDesc.SetBackgroundColour(wx.Colour(255, 226, 154))
        self.lblObjName.SetBackgroundColour(wx.Colour(255, 226, 154))
        self.lblObjName.SetFont(wx.Font(8, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.lblClassNameDesc.SetBackgroundColour(wx.Colour(255, 226, 154))
        self.lblClassName.SetBackgroundColour(wx.Colour(255, 226, 154))
        self.lblClassName.SetFont(wx.Font(8, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.LblObjectIDDesc.SetBackgroundColour(wx.Colour(255, 226, 154))
        self.lblObjectID.SetBackgroundColour(wx.Colour(255, 226, 154))
        self.lblObjectID.SetFont(wx.Font(8, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        for ctl in self.attribTexts:
            ctl.Enable(False)
        #self.txtVar0.Enable(False)
        #self.txtVar1.Enable(False)
        #self.txtVar2.Enable(False)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: WindowObjectInspector.__do_layout
        szMain = wx.BoxSizer(wx.VERTICAL)
        szSizer = wx.BoxSizer(wx.VERTICAL)
        szVars = wx.GridSizer(len(self.attributes), 2, 0, 0)
        szInfo = wx.GridSizer(3, 2, 0, 0)
        szInfo.Add(self.lblObjNameDesc, 0, wx.EXPAND, 0)
        szInfo.Add(self.lblObjName, 0, wx.EXPAND, 0)
        szInfo.Add(self.lblClassNameDesc, 0, wx.EXPAND, 0)
        szInfo.Add(self.lblClassName, 0, wx.EXPAND, 0)
        szInfo.Add(self.LblObjectIDDesc, 0, wx.EXPAND, 0)
        szInfo.Add(self.lblObjectID, 0, wx.EXPAND, 0)
        szSizer.Add(szInfo, 1, wx.EXPAND, 0)

        for i in range(len(self.attributes)):
            szVars.Add(self.attribLabels[i], 0, 0, 0)
            szVars.Add(self.attribTexts[i], 0, 0, 0)

        szSizer.Add(szVars, 1, wx.EXPAND, 0)
        szMain.Add(szSizer, 1, wx.EXPAND, 0)
        self.SetSizer(szMain)
        szMain.Fit(self)
        self.Layout()
        # end wxGlade

    def refreshVars(self, event):
        for i in range(len(self.attributes)):
            self.attribTexts[i].SetValue( str(getattr( self.introspectionObject.objectPointer, self.attributes[i] )) )

    def onCloseWindow(self, event):
        self.timer.Stop()
        self.Destroy()
