# -*- coding: iso-8859-15 -*-
# generated by wxGlade 0.6.3 on Mon Jan 17 15:41:18 2011

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode

# end wxGlade

class WindowCreateObject(wx.Dialog):
    def __init__(self, classList, *args, **kwds):
        # begin wxGlade: WindowCreateObject.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.lstClasses = wx.ListBox(self, -1, choices=classList)
        self.btnCreate = wx.Button(self, -1, "Create")
        self.btnCreate.Bind(wx.EVT_BUTTON, self.createClick)
        self.btnCancel = wx.Button(self, -1, "Cancel")
        self.btnCancel.Bind(wx.EVT_BUTTON, self.cancelClick)
        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: WindowCreateObject.__set_properties
        self.SetTitle("Select class for new object")
        self.SetSize((379, 150))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: WindowCreateObject.__do_layout
        szMain = wx.BoxSizer(wx.VERTICAL)
        szButtons = wx.BoxSizer(wx.HORIZONTAL)
        szMain.Add(self.lstClasses, 0, wx.EXPAND, 0)
        szButtons.Add(self.btnCreate, 0, 0, 0)
        szButtons.Add(self.btnCancel, 0, 0, 0)
        szMain.Add(szButtons, 1, wx.EXPAND, 0)
        self.SetSizer(szMain)
        self.Layout()

        # end wxGlade
    def getSelection(self):
        return self.lstClasses.GetStringSelection()

    def createClick(self, event):
        self.EndModal(1)

    def cancelClick(self, event):
        self.EndModal(0)
# end of class WindowCreateObject
