# -*- coding: iso-8859-15 -*-
# generated by wxGlade 0.6.3 on Mon Jan 17 15:41:18 2011

import wx, os, sys
from WindowGetParams import WindowGetParams
from WindowCreateObject import WindowCreateObject
from ObjectPanel import ObjectPanel
from IntrospectionTools import *

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode

# end wxGlade

class WindowMain(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: WindowMain.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.pnlObjects = ObjectPanel(self, -1)
        self.pnlObjects.SetBackgroundColour(wx.Colour(250, 255, 255))
        self.btnLoadScript = wx.Button(self, -1, "Load Script")
        self.btnLoadScript.Bind(wx.EVT_BUTTON, self.loadScriptClick)
        self.btnCreateObj = wx.Button(self, -1, "Create Object")
        self.btnCreateObj.Disable()
        self.btnCreateObj.Bind(wx.EVT_BUTTON, self.createObjectClick)
        self.btnQuit = wx.Button(self, -1, "Quit")
        self.btnQuit.Bind(wx.EVT_BUTTON, self.quitClick)
        self.lstActivity = wx.ListBox(self, -1, choices=[])

        wx.GetApp().SetBenchWidget(self.pnlObjects)
        self.__set_properties()
        self.__do_layout()
        self.lstActivity.Append('Welcome to Object Introspection Demo.')
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: WindowMain.__set_properties
        self.SetTitle("Object Introspection Demo")
        self.SetSize((800, 600))
        self.pnlObjects.load()
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: WindowMain.__do_layout
        szMain = wx.BoxSizer(wx.VERTICAL)
        szButtons = wx.BoxSizer(wx.HORIZONTAL)
        szMain.Add(self.pnlObjects, 1, wx.EXPAND, 0)
        szButtons.Add(self.btnLoadScript, 0, wx.EXPAND, 0)
        szButtons.Add(self.btnCreateObj, 0, wx.EXPAND, 0)
        szButtons.Add(self.btnQuit, 0, wx.EXPAND, 0)
        szMain.Add(szButtons, 0, wx.EXPAND|wx.ALIGN_CENTER_HORIZONTAL, 0)
        szMain.Add(self.lstActivity, 0, wx.EXPAND, 0)
        self.SetSizer(szMain)
        self.Layout()
        # end wxGlade

    def loadScriptClick(self, event):
        if wx.GetApp().GetOpenFile() == "":
            #self.btnLoadScript.Disable()
            dlg = wx.FileDialog(self, "Choose a file", os.getcwd(), "", "*.py", wx.OPEN)
            if dlg.ShowModal() == wx.ID_OK:
                path = dlg.GetPath()
                self.SetTitle("Object Introspection Demo (" + path + ")")
                wx.GetApp().SetOpenFile(path)
                wx.GetApp().LogMessage('Loaded: '+path)
                self.btnCreateObj.Enable()
            dlg.Destroy()
        else:
            dlg = wx.MessageDialog(None, 'Are you sure? Loading another script will clear your current bench', 'Object Introspection Demo', wx.YES_NO | wx.NO_DEFAULT | wx.ICON_QUESTION)
            if dlg.ShowModal() == wx.ID_YES:
                wx.GetApp().ResetApplication()



    def createObjectClick(self, event):
        dlg = WindowCreateObject(getScriptClasses(getOpenScriptScope()),None, -1, "")
        if dlg.ShowModal() == 1:
            item = dlg.getSelection()
            params = getConstructorParams(item)
            dlg2 = WindowGetParams(params, None, -1, "")
            if dlg2.ShowModal() == 1:
                o = constructObjectDynamic(item, dlg2.getParams())
                oName = 'obj'+str(self.pnlObjects.amountOfObjects())
                self.pnlObjects.addObject( IntrospectionObject(oName,item, o ) )
                wx.GetApp().LogMessage('Created object "' + oName + '" of type "' + item + '"')
            dlg2.Destroy()
        dlg.Destroy()

    def quitClick(self, event):
        dlg = wx.MessageDialog(None, 'Are you sure to quit?', 'Object Introspection Demo', wx.YES_NO | wx.NO_DEFAULT | wx.ICON_QUESTION)
        if dlg.ShowModal() == wx.ID_YES:
            self.Destroy()

# end of class WindowMain
